version: '3'
services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: btc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
        
